import { Room, Review } from './types';

// Cloudbeds booking URL - all rooms book via the same portal
export const CLOUDBEDS_BOOKING_URL = 'https://us2.cloudbeds.com/en/reservation/eh45iO';

export const ROOMS: Room[] = [
  {
    id: 'doble-privado',
    name: 'Habitacion Doble con Bano Privado',
    nameEn: 'Double Room with Private Bathroom',
    nameFr: 'Chambre Double avec Salle de Bain Privee',
    nameAr: 'غرفة مزدوجة مع حمام خاص',
    description: 'Nuestra habitacion mas solicitada para parejas. Decoracion sencilla y acogedora con muebles de madera de pino, cama doble comoda, bano completo privado dentro de la habitacion, climatizacion y suelo de baldosa tradicional.',
    descriptionEn: 'Our most popular room for couples. Features simple, welcoming decor with classic solid pine wood furniture, a comfortable double bed, a full en-suite private bathroom, climate control/fan, and traditional tiled flooring.',
    descriptionFr: 'Notre chambre la plus demandee pour les couples. Decoration simple et chaleureuse, mobilier en pin massif, lit double confortable, climatisation et salle de bain privee.',
    descriptionAr: 'غرفتنا الأكثر شعبية للأزواج. ديكور بسيط وترحيبي مع أثاث من خشب الصنوبر، وسرير مزدوج مريح، وحمام خاص كامل، ونظام تكييف.',
    type: 'doble',
    bathroom: 'private',
    price: 58,
    image: '/images/rooms/doble-privado-1.jpg',
    images: [
      '/images/rooms/doble-privado-1.jpg',
      '/images/rooms/doble-privado-4.jpg',
      '/images/rooms/doble-privado-5.jpg',
      '/images/rooms/doble-privado-6.jpg',
      '/images/rooms/doble-privado-7.jpg',
      '/images/rooms/doble-privado-8.jpg',
    ],
    amenities: ['Bano Privado', 'Aire Acondicionado', 'Smart TV', 'Wi-Fi Gratis', 'Muebles de Pino', 'Suelo de Baldosa', 'Ropa de Cama y Toallas', 'Armario'],
    amenitiesEn: ['Private Bathroom', 'Air Conditioning', 'Smart TV', 'Free Wi-Fi', 'Pine Wood Furniture', 'Tiled Floor', 'Bed Linens & Towels', 'Wardrobe'],
    amenitiesFr: ['Salle de Bain Privee', 'Climatisation', 'Smart TV', 'Wi-Fi Gratuit', 'Meubles en Pin', 'Sol en Carrelage', 'Draps & Serviettes', 'Armoire'],
    amenitiesAr: ['حمام خاص', 'تكييف هواء', 'تلفزيون ذكي', 'واي فاي مجاني', 'أثاث خشب الصنوبر', 'أرضية بلاط', 'بياضات ومناشف', 'خزانة ملابس'],
    maxGuests: 2,
    featured: true,
  },
  {
    id: 'triple-privado',
    name: 'Habitacion Triple con Bano Privado',
    nameEn: 'Triple Room with Private Bathroom',
    nameFr: 'Chambre Triple avec Salle de Bain Privee',
    nameAr: 'غرفة ثلاثية مع حمام خاص',
    description: 'Perfecta para pequenas familias o grupo de tres amigos. Tres camas individuales o una doble y una individual de pino espanol, abundante luz natural, bano privado completo y ventilador o aire acondicionado.',
    descriptionEn: 'Perfect for small families or groups of three friends. Three single beds (or one double and one single) of Spanish pine, natural light, full private bathroom, and ceiling fan or A/C.',
    descriptionFr: 'Ideal pour les petites familles ou les groupes de trois amis. Trois lits simples en pin espagnol, lumiere naturelle, salle de bain privee.',
    descriptionAr: 'مثالية للعائلات الصغيرة أو مجموعة ثلاثة أصدقاء. ثلاثة أسرة فردية، إضاءة طبيعية، وحمام خاص كامل.',
    type: 'triple',
    bathroom: 'private',
    price: 75,
    image: '/images/rooms/triple-privado-1.jpg',
    images: [
      '/images/rooms/triple-privado-1.jpg',
      '/images/rooms/triple-privado-2.jpg',
      '/images/rooms/triple-privado-3.jpg',
      '/images/rooms/triple-privado-4.jpg',
      '/images/rooms/triple-privado-5.jpg',
      '/images/rooms/triple-privado-6.jpg',
    ],
    amenities: ['Bano Privado', 'Aire Acondicionado', 'Smart TV', 'Wi-Fi Gratis', 'Muebles de Pino', 'Suelo de Baldosa', 'Ropa de Cama y Toallas', 'Escritorio'],
    amenitiesEn: ['Private Bathroom', 'Air Conditioning', 'Smart TV', 'Free Wi-Fi', 'Pine Wood Furniture', 'Tiled Floor', 'Bed Linens & Towels', 'Desk'],
    amenitiesFr: ['Salle de Bain Privee', 'Climatisation', 'Smart TV', 'Wi-Fi Gratuit', 'Meubles en Pin', 'Sol en Carrelage', 'Draps & Serviettes', 'Bureau'],
    amenitiesAr: ['حمام خاص', 'تكييف هواء', 'تلفزيون ذكي', 'واي فاي مجاني', 'أثاث خشب الصنوبر', 'أرضية بلاط', 'بياضات ومناشف', 'مكتب'],
    maxGuests: 3,
    featured: true,
  },
  {
    id: 'cuadruple-privado',
    name: 'Habitacion Familiar Cuadruple (Bano Privado)',
    nameEn: 'Quadruple Family Room (Private Bathroom)',
    nameFr: 'Chambre Familiale Quadruple (Salle de Bain Privee)',
    nameAr: 'غرفة عائلية رباعية (حمام خاص)',
    description: 'Nuestra habitacion mas grande e ideal para familias. Camas individuales de pino o distribuciones mixtas, ventilador o climatizacion, gran armario rustico y bano privado completo.',
    descriptionEn: 'Our largest room, ideal for families. Solid pine single beds or mixed bedding, ceiling fan or A/C, large rustic wardrobe, and full private bathroom.',
    descriptionFr: 'Notre chambre la plus grande, ideale pour les familles. Lits en pin, grand armoire rustique et salle de bain privee.',
    descriptionAr: 'غرفتنا الأكبر، مثالية للعائلات. أسرة فردية من خشب الصنوبر أو توزيعات مختلطة، وحمام خاص كامل.',
    type: 'cuadruple',
    bathroom: 'private',
    price: 90,
    image: '/images/rooms/cuadruple-privado-1.jpg',
    images: [
      '/images/rooms/cuadruple-privado-1.jpg',
      '/images/rooms/cuadruple-privado-2.jpg',
      '/images/rooms/cuadruple-privado-3.jpg',
      '/images/rooms/cuadruple-privado-4.jpg',
    ],
    amenities: ['Bano Privado', 'Aire Acondicionado', 'Smart TV', 'Wi-Fi Gratis', 'Suelo de Baldosa', 'Muebles de Pino', 'Ropa de Cama y Toallas'],
    amenitiesEn: ['Private Bathroom', 'Air Conditioning', 'Smart TV', 'Free Wi-Fi', 'Tiled Floor', 'Pine Wood Furniture', 'Bed Linens & Towels'],
    amenitiesFr: ['Salle de Bain Privee', 'Climatisation', 'Smart TV', 'Wi-Fi Gratuit', 'Sol en Carrelage', 'Meubles en Pin', 'Draps & Serviettes'],
    amenitiesAr: ['حمام خاص', 'تكييف هواء', 'تلفزيون ذكي', 'واي فاي مجاني', 'أرضية بلاط', 'أثاث خشب الصنوبر', 'بياضات ومناشف'],
    maxGuests: 4,
    featured: false,
  },
  {
    id: 'doble-compartido',
    name: 'Habitacion Doble Economica (Bano Compartido)',
    nameEn: 'Budget Double Room (Shared Bathroom)',
    nameFr: 'Chambre Double Economique (Salle de Bain Partagee)',
    nameAr: 'غرفة مزدوجة اقتصادية (حمام مشترك)',
    description: 'La opcion con mejor relacion calidad-precio. Cama doble comoda, muebles tradicionales de pino, ventilador silencioso y acceso a banos compartidos impecables en el pasillo (desinfeccion constante).',
    descriptionEn: 'Our best-value option. Comfortable double bed, traditional pine furniture, quiet ceiling fan, and access to pristine shared bathrooms cleaned multiple times daily.',
    descriptionFr: 'Notre option avec le meilleur rapport qualite-prix. Lit double confortable, meuble en pin, ventilateur et acces aux salles de bain communes impeccables.',
    descriptionAr: 'الخيار الأنسب من حيث السعر والقيمة. سرير مزدوج مريح، وأثاث صنوبر تقليدي، ومروحة هادئة، ووصول إلى حمامات مشتركة نظيفة.',
    type: 'doble',
    bathroom: 'shared',
    price: 45,
    image: '/images/rooms/doble-compartido-3.jpg',
    images: [
      '/images/rooms/doble-compartido-3.jpg',
      '/images/rooms/doble-compartido-1.png',
      '/images/rooms/doble-compartido-2.png',
    ],
    amenities: ['Bano Compartido', 'Ventilador de Techo', 'Television', 'Wi-Fi Gratis', 'Muebles de Pino', 'Suelo de Baldosa', 'Ropa de Cama y Toallas', 'Espejo'],
    amenitiesEn: ['Shared Bathroom', 'Quiet Ceiling Fan', 'Television', 'Free Wi-Fi', 'Pine Wood Furniture', 'Tiled Floor', 'Bed Linens & Towels', 'Mirror'],
    amenitiesFr: ['Salle de Bain Partagee', 'Ventilateur de Plafond', 'Television', 'Wi-Fi Gratuit', 'Meubles en Pin', 'Sol en Carrelage', 'Draps & Serviettes', 'Miroir'],
    amenitiesAr: ['حمام مشترك', 'مروحة سقف', 'تلفزيون', 'واي فاي مجاني', 'أثاث خشب الصنوبر', 'أرضية بلاط', 'بياضات ومناشف', 'مرآة'],
    maxGuests: 2,
    featured: false,
  },
  {
    id: 'individual-compartido',
    name: 'Habitacion Individual Economica (Bano Compartido)',
    nameEn: 'Budget Single Room (Shared Bathroom)',
    nameFr: 'Chambre Individuelle Economique (Salle de Bain Partagee)',
    nameAr: 'غرفة فردية اقتصادية (حمام مشترك)',
    description: 'Perfecta para viajeros en solitario y profesionales. Cama individual, decoracion sencilla, mesa auxiliar y armario de pino, ventilador silencioso, Wi-Fi rapido y banos comunes siempre limpios.',
    descriptionEn: 'Perfect for solo travelers and professionals. Single bed, simple decor, pine side table and wardrobe, quiet ceiling fan, high-speed Wi-Fi, and clean shared bathrooms.',
    descriptionFr: 'Parfait pour les voyageurs en solo et professionnels. Lit simple, meuble en pin, ventilateur et Wi-Fi haut debit. Salles de bain communes impeccables.',
    descriptionAr: 'مثالية للمسافرين المنفردين. سرير فردي وأثاث صنوبر ومروحة هادئة وواي فاي سريع وحمامات مشتركة نظيفة.',
    type: 'individual',
    bathroom: 'shared',
    price: 32,
    image: '/images/rooms/individual-compartido-1.png',
    images: [
      '/images/rooms/individual-compartido-1.png',
      '/images/rooms/individual-compartido-2.png',
      '/images/rooms/individual-compartido-3.png',
    ],
    amenities: ['Bano Compartido', 'Ventilador de Techo', 'Wi-Fi Gratis', 'Muebles de Pino', 'Suelo de Baldosa', 'Ropa de Cama y Toallas', 'Escritorio Pequeno'],
    amenitiesEn: ['Shared Bathroom', 'Quiet Ceiling Fan', 'Free Wi-Fi', 'Pine Wood Furniture', 'Tiled Floor', 'Bed Linens & Towels', 'Small Desk'],
    amenitiesFr: ['Salle de Bain Partagee', 'Ventilateur de Plafond', 'Wi-Fi Gratuit', 'Meubles en Pin', 'Sol en Carrelage', 'Draps & Serviettes', 'Petit Bureau'],
    amenitiesAr: ['حمام مشترك', 'مروحة سقف', 'واي فاي مجاني', 'أثاث خشب الصنوبر', 'أرضية بلاط', 'بياضات ومناشف', 'مكتب صغير'],
    maxGuests: 1,
    featured: false,
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author: 'Manuel J. Garcia',
    rating: 5,
    date: '2026-05-18',
    comment: 'Una excelente sorpresa. El Hostal esta super limpio, huele genial al entrar. Arroyo de la Miel tiene mucha vida y la estacion de tren esta literal a 3 minutos andando. Volvere sin duda.',
    language: 'es',
    source: 'Booking.com',
  },
  {
    id: 'rev-2',
    author: 'Sarah M.',
    rating: 5,
    date: '2026-04-22',
    comment: 'Absolutely loved my stay! The hostel is spotless, the staff are incredibly warm, and the location is unbeatable. Just a 3-minute walk from the train to Malaga airport and beach.',
    language: 'en',
    source: 'Google',
  },
  {
    id: 'rev-3',
    author: 'Ahmed B.',
    rating: 5,
    date: '2026-05-30',
    comment: 'مكان رائع ونظيف جداً. الموقع ممتاز قريب من محطة القطار والشاطئ. الأسرة نظيفة والخدمة عائلية دافئة. سأعود بالتأكيد.',
    language: 'ar',
    source: 'Booking.com',
  },
  {
    id: 'rev-4',
    author: 'Sophie L.',
    rating: 5,
    date: '2026-06-01',
    comment: 'Etablissement tres propre et bien situe a Arroyo de la Miel. Tres bon rapport qualite-prix. Personnel accueillant et sympathique. Je recommande vivement!',
    language: 'fr',
    source: 'TripAdvisor',
  },
  {
    id: 'rev-5',
    author: 'Carlos F.',
    rating: 5,
    date: '2026-06-10',
    comment: 'Segunda vez que me alojo aqui y siempre genial. La limpieza es impecable, el precio es justo y la ubicacion inmejorable. La atencion es de 10.',
    language: 'es',
    source: 'Booking.com',
  },
];

export const NEARBY_SIGHTS = [
  { name: 'Estacion Arroyo de la Miel', nameEn: 'Arroyo de la Miel Train Station', distance: '200 metros (3 min)', distanceEn: '200 meters (3 min walk)', icon: 'train', description: 'Conecta directo con el Aeropuerto de Malaga (15 min) y el centro de Malaga (25 min) via C-1.', descEs: 'Conecta directo con el Aeropuerto de Malaga (15 min) y el centro de Malaga (25 min) via C-1.', descEn: 'Connects directly with Malaga Airport (15 min) and Malaga Center (25 min) via the C-1 train line.', descriptionEn: 'Connects directly with Malaga Airport (15 min) and Malaga Center (25 min) via the C-1 train line.' },
  { name: 'Teleférico de Benalmadena', nameEn: 'Benalmadena Cable Car', distance: '600 metros (8 min)', distanceEn: '600 meters (8 min walk)', icon: 'mountain', description: 'Sube a la cima del Monte Calamorro para vistas espectaculares de la costa.', descEs: 'Sube a la cima del Monte Calamorro para vistas espectaculares de la costa.', descEn: 'Ride to the top of Mount Calamorro for spectacular views of the Malaga coast.', descriptionEn: 'Ride to the top of Mount Calamorro for spectacular views of the Malaga coast.' },
  { name: 'Playas de Benalmadena', nameEn: 'Benalmadena Beaches', distance: '1.5 km (15-20 min)', distanceEn: '1.5 km (15-20 min walk)', icon: 'beach', description: 'Playas de arena fina con chiringuitos y ambiente mediterraneo.', descEs: 'Playas de arena fina con chiringuitos y ambiente mediterraneo.', descEn: 'Fine sand beaches with seafood restaurants and Mediterranean atmosphere.', descriptionEn: 'Fine sand beaches with seafood restaurants and Mediterranean atmosphere.' },
  { name: 'Puerto Marina Benalmadena', nameEn: 'Puerto Marina (Marina)', distance: '2.2 km (5 min)', distanceEn: '2.2 km (5 min by car)', icon: 'anchor', description: 'Uno de los puertos deportivos mas bellos del mundo, con tiendas, restaurantes y acuario.', descEs: 'Uno de los puertos deportivos mas bellos del mundo, con tiendas, restaurantes y acuario.', descEn: 'One of the most beautiful marinas in the world with shops, dining and Sea Life aquarium.', descriptionEn: 'One of the most beautiful marinas in the world with shops, dining and Sea Life aquarium.' },
  { name: 'Parque de la Paloma', nameEn: 'Parque de la Paloma', distance: '1.1 km (12 min)', distanceEn: '1.1 km (12 min walk)', icon: 'trees', description: 'Precioso parque con animales sueltos, jardines de cactus y lagos artificiales.', descEs: 'Precioso parque con animales sueltos, jardines de cactus y lagos artificiales.', descEn: 'Beautiful park with free-roaming animals, cactus gardens and artificial lakes.', descriptionEn: 'Beautiful park with free-roaming animals, cactus gardens and artificial lakes.' },
  { name: 'Aeropuerto AGP', nameEn: 'Malaga Airport (AGP)', distance: '15 min en tren', distanceEn: '15 min by train', icon: 'plane', description: 'Aeropuerto Malaga-Costa del Sol via cercanias C-1 desde la estacion.', descEs: 'Aeropuerto Malaga-Costa del Sol via cercanias C-1 desde la estacion.', descEn: 'Malaga-Costa del Sol Airport via C-1 Cercanias train from the station.', descriptionEn: 'Malaga-Costa del Sol Airport via C-1 Cercanias train from the station.' },
];
